### PR TITLE
fix: Use choicelist values for macros

### LINKED ISSUE #231: Integrate macros CK5
### Context / Problem to solve / Design
Jahia provides macros to make some content dynamic in rich-text areas
In CK4 we provide a dropdown list of macros
In CK5 this feature has not been integrated

TBD : add that by defaut in some of jahia toolbars, or provide a plug-in so the customers can create their own configs with this feature ?

### Story
As an editor
I want to simply insert macros in my rich-texts

## Testable scenarios

**Setup**
Given

**Case 1**
When 
Then 

**Case N**
When 
Then 

### Test Strategy
Cypress tests?

### Labels 
En: 
Fr: 
De:

### PR DESCRIPTION
**Pull request by AKarmanov**
### Description
Use choicelist values for macros. Cache the value for 30 seconds to prevent over querying when macros is required. Add config to be able to exclude certain macros from the list. If no values are found nothing happens, we don't display anything.

#### Source code
- [ ] I've shared and documented any breaking change
- [ ] I've reviewed and updated the jahia-depends

#### Tests
- [ ] I've provided Unit and/or Integration Tests
- [ ] I've updated the parent issue with required manual validations

> [!TIP]
> Documentation to guide the reviews: [How to do a code review](https://jahia-confluence.atlassian.net/wiki/spaces/PR/pages/2064660/How+to+do+a+code+review+-+Ref+ISSOP08.A14006)

### CODE REVIEW

File: src/javascript/CKEditor/configurations/mention/mentionConfig.js [hunk 1]
```diff
@@ -10,36 +10,72 @@ export const mentionConfig = {
...
+                    // Update cache
+                    cachedData = json;
+                    cacheTimestamp = Date.now();
+
+                    const filteredItems = filterAndProcessItems(json, queryText);
+                    resolve(filteredItems);
+                }
+            });
+        } catch (e) {
+            console.error('Failed to call macros initializer', e);
```
Comment (gflores-jahia) [inline src/javascript/CKEditor/configurations/mention/mentionConfig.js]: Downgrade to warn maybe ? possible macros is not installed as intended. We could also add to 'check for macros install' as part of message too.

**Review by gflores-jahia — DISMISSED** [review]
Looks good, added suggestions about error message.

File: src/javascript/CKEditor/configurations/mention/mentionConfig.js (hunk 1 above)
Comment (AKarmanov) [reply src/javascript/CKEditor/configurations/mention/mentionConfig.js]: This is going to to happen in the case of network error, meaning we don't even send the request, there is an issue with fetch, server fails or something like this. If macros is not available we get a clean 200 with empty array. But yeah I can downgrade and add one in case initializer api returns nothing.

**Review by gflores-jahia — APPROVED** [review]
